SELECT  b.AUTHOR_ID, AUTHOR_NAME, CATEGORY,sum(SALES*PRICE) TOTAL_SALES
from BOOK_SALES bs
left join BOOK b
on bs.BOOK_ID = b.BOOK_ID
left join AUTHOR a
on b.AUTHOR_ID = a.AUTHOR_ID
where SALES_DATE like  "2022-01%"
group by b.AUTHOR_ID, CATEGORY
order by b.AUTHOR_ID, CATEGORY desc