with sale
as(
select SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE like"2022-03%"

    union
    
select SALES_DATE,PRODUCT_ID, null as USER_ID,SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE like"2022-03%"

)

select date_format(SALES_DATE,"%Y-%m-%d") SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
from sale
order by SALES_DATE, PRODUCT_ID, USER_ID