-- 코드를 입력하세요
SELECT fo.PRODUCT_ID, fr.PRODUCT_NAME, (sum(fo.AMOUNT)*fr.PRICE) TOTAL_SALES
from FOOD_ORDER fo inner join FOOD_PRODUCT fr
on fo.PRODUCT_ID = fr.PRODUCT_ID
WHERE Fo.PRODUCE_DATE >= '2022-05-01' AND Fo.PRODUCE_DATE <= '2022-05-31'
group by fo.PRODUCT_ID
order by TOTAL_SALES desc, fo.PRODUCT_ID


# SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, (SUM(FO.AMOUNT) * FP.PRICE) AS TOTAL_SALES
# FROM FOOD_PRODUCT FP INNER JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
# WHERE FO.PRODUCE_DATE >= '2022-05-01' AND FO.PRODUCE_DATE <= '2022-05-31'
# GROUP BY FO.PRODUCT_ID
# ORDER BY 3 DESC, 1 ASC;