-- 코드를 입력하세요
SELECT ICECREAM_INFO.INGREDIENT_TYPE, sum(TOTAL_ORDER) TOTAL_ORDER
From FIRST_HALF left join ICECREAM_INFO
on FIRST_HALF.FLAVOR =ICECREAM_INFO.FLAVOR
group by INGREDIENT_TYPE
order by TOTAL_ORDER